### ISSUE TITLE
apiserver_cert_extra_sans has no effect

### ISSUE THREAD

**Issue by flostru** [puppetlabs/puppetlabs-kubernetes#283]
## What you expected to happen?

We need to add a loadbalanced IP or alternatively a floating IP as entry for the apiserver.
Additionally a fqdn.

## What happened?
Obviously the Param "apiserver_cert_extra_sans" (apiServerCertSANs) is either outdated or missused at the wrong place.

Certs dont get the SANs
```bash
kubectl get nodes
Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 172.16.72.21, not 172.16.72.10
```
```bash
openssl x509 -in /etc/kubernetes/pki/apiserver.crt -text -noout
--snip--
            X509v3 Subject Alternative Name: 
                DNS:ctrl01, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.96.0.1, IP Address:172.16.72.21
--snip--
```
## How to reproduce it?
```yaml
kubernetes::apiserver_cert_extra_sans:
  # haproxied IP or floating ip (keepalived)
  - '172.16.72.100'
  - 'api.example.com'
```
resulting /etc/kubernetes/config.yaml
```yaml
---snip---
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta1
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ""
controllerManager: {}
dns:
  type: CoreDNS
etcd:
    external:
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/etcd/client.crt
        endpoints:
          - https://ctrl01:2379
          - https://ctrl02:2379
          - https://ctrl03:2379
        keyFile: /etc/kubernetes/pki/etcd/client.key
imageRepository:  k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.13.5
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServerCertSANs:
- 172.16.72.100
- api.example.com
---snip---
```
## Versions:
```
$ puppet --version

5.5.14

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"

$ docker version OR crictl version

Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ facter os

{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.9 (stretch)",
    id => "Debian",
    release => {
      full => "9.9",
      major => "9",
      minor => "9"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.9",
    major => "9",
    minor => "9"
  },
  selinux => {
    enabled => false
  }
}
```
## Logs:
```
---snip--
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[ctrl01]/Exec[kubeadm init]/returns: W0508 12:09:45.408939    5227 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta1", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"
---snip---
```
