### ISSUE TITLE
apiserver_extra_volumes and controllermanager_extra_volumes no longer set readOnly attribute (regression)

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#302]
## What you expected to happen?

Given a kubernetes::apiserver_extra_volume hash as follows:

```
kubernetes::apiserver_extra_volumes:
  var-log:
    hostPath: '/var/log'
    mountPath: '/var/log'
    readOnly: 'false'
  audit-policy:
    hostPath: '/etc/kubernetes-audit-policy.yaml'
    mountPath: '/etc/kubernetes-audit-policy.yaml'
    readOnly: 'true'
```

I would expect the readOnly to be set in config.yaml

## What happened?

The kubeadm config templates do not set readOnly

## How to reproduce it?

Define extra_volumes in hiera which have readOnly. Observe that readOnly does not get set in /etc/kubernetes/config.yaml.

## Additional Information
extra_volumes was originally implemented in https://github.com/puppetlabs/puppetlabs-kubernetes/pull/89 and supported readOnly. When the module was redesigned to use kubeadm, readOnly was simply forgotten in the kubeadm config templates.

## Versions:
```
kubernetes puppet module 4.0.1

$ puppet --version

4.7.0

$ kubectl version

1.14.1
