### ISSUE TITLE
apiserver_extra_volumes does not let me set a host path type

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#304]
The current implementation of apiserver_extra_volumes in the module, does not allow the specifying of a pathType for a mount.

This means that the resultant kube-apiserver pod spec yaml ends up containing 'type: ""' for each mount defined via apiserver_extra_volumes.

e.g.
```
  volumes:
  - hostPath:
      path: /etc/kubernetes-audit-policy.yaml
      type: ""
    name: audit-policy
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /var/log
      type: ""
    name: var-log
```

This means I can't define whether my mounts are File, Directory, etc. This makes the feature unusable.

kubeadm config spec supports a parameter pathType:

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1
```
type HostPathMount struct {
    // Name of the volume inside the pod template.
    Name string `json:"name"`
    // HostPath is the path in the host that will be mounted inside
    // the pod.
    HostPath string `json:"hostPath"`
    // MountPath is the path inside the pod where hostPath will be mounted.
    MountPath string `json:"mountPath"`
    // ReadOnly controls write access to the volume
    ReadOnly bool `json:"readOnly,omitempty"`
    // PathType is the type of the HostPath.
    PathType v1.HostPathType `json:"pathType,omitempty"`
}

  extraVolumes:
  - name: "some-volume"
    hostPath: "/etc/some-path"
    mountPath: "/etc/some-pod-path"
    readOnly: false
    pathType: File
```
The best fix therefore is to add support for pathType to the module. This could be done at the same time as re-adding support for readOnly (see https://github.com/puppetlabs/puppetlabs-kubernetes/issues/302)

## Versions:
```
kubernetes puppet module 4.0.1

$ puppet --version

4.7.0

$ kubectl version

1.14.1
